version: '3.1'

services:

  db:
    image: mysql:8.2.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

    volumes:
      - ./local_db/state:/var/lib/mysql
      # - ./local_db/scripts/init.sql:/docker-entrypoint-initdb.d/0.sql